server:
    port: 3030

spring:
    temporal:
        connection:
            target: 127.0.0.1:7233
            target.namespace: default
        workersAutoDiscovery:
            packages: com.github.hronom.temporalplaygroundusers
